### ISSUE TITLE
Create new register and login page 

### ISSUE THREAD

**Issue by James-N-M** [James-N-M/box-off#12]
http://box-off.test/login && http://box-off.test/register currently have little to no styling and anything would potentially look better. Bootstrap v-4 is used through out the application so try to stick with using bootstrap. 

Steps 
[ ] create a branch for the issue 
[ ] Navigate to http://box-off.test/register
[ ] in the code both views are located at box-off/resources/views/auth
[ ] your free to replace everything in-side of @section('content') 
[ ] make sure the form has ```  <form method="POST" action="{{ route('login') }}">
                        @csrf ``` or it wont submit properly when registering a user
[ ] make sure the form has the same fields as the old version refer to the github repo for the original.
[ ] submit a Pull request

**Comment by harshyadav9** [comment]
I would like to take this issue.

**Comment by James-N-M** [comment]
@harshyadav9 That'd be awesome ! let me know if you need any help !
